### ISSUE TITLE
QGMC710 - Buttons not working

### ISSUE THREAD

**Issue by cdelarge3** [cpuwolf/Quickmadedevice#1]
Hi CPUWolf, I'm having an issue with my QGMC710. The buttons on the panel that are not associated with a knob appear to have stopped working (all of them).  In the windows controller testing window, they don't register key presses. I've tried this on separate computers, running Win11 on 1 and Win10 on the other.  Could this be a driver issue?  The knobs and the roller work as expected, while the AP buttons fail to function.  Possible driver issue?  I have what I assume is a pretty early version of it.  Can you help?

Thanks!

**Comment by slapshot75** [comment]
Hi cdelarge3  and cpuwolf, i have exactly the same issue. Any news or help?
best regards

**Comment by cdelarge3** [comment]
hi @slapshot75 I also just posted here since I've gotten no response. https://github.com/quickmake/QGMC710/issues/13

I'm not sure if @cpuwolf is looking here.

**Comment by quickmade** [comment]
@cdelarge3 @slapshot75  Please contact me : quickmade@qq.com

**Comment by cpuwolf** [comment]
HW issues

**Comment by slapshot75** [comment]
but i can not resolved it by myself.

**Comment by cdelarge3** [comment]
@cpuwolf I sent an email to quickmade, late unfortunately since I didn't get the reply notification. Can you ask him to reply? Thank you.
